[application]

[web.app]

# HTML title tag content
title = "posot_thai"

# แก้ไข: กำหนดเป็น "/posot_thai" เพื่อให้ใช้งานบน GitHub Pages ได้และแก้ปัญหาจอขาว
# (หมายเหตุ: หากคุณต้องการรันดูผลลัพธ์ในเครื่อง localhost:8080 ชั่วคราว ให้คอมเมนต์บรรทัดนี้ไว้ก่อนด้วยเครื่องหมาย # ครับ)
base_path = "/posot_thai"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []